<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="blockModelingMetamodel" nsURI="http://www.example.org/blockModelingMetamodel"
    nsPrefix="blockModelingMetamodel">
  <eClassifiers xsi:type="ecore:EEnum" name="Category">
    <eLiterals name="MOVEMENT" literal="MOVEMENT"/>
    <eLiterals name="DETECTION" value="1"/>
    <eLiterals name="SOUND" value="2"/>
    <eLiterals name="TOOLS" value="3"/>
    <eLiterals name="VARIOUS" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Cursor">
    <eLiterals name="DEFAULT"/>
    <eLiterals name="HELP" value="1"/>
    <eLiterals name="POINTER" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImageBackgroundShape">
    <eLiterals name="CIRCLE"/>
    <eLiterals name="SQUARE" value="1"/>
    <eLiterals name="HEXAGON" value="2"/>
    <eLiterals name="OCTAGON" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComparisonType">
    <eLiterals name="NONE"/>
    <eLiterals name="SELECT" value="1"/>
    <eLiterals name="INPUT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BlockApp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasBlock" lowerBound="1"
        eType="#//Block" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" ordered="false"
        unique="false" lowerBound="1" eType="#//Category"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="backroundColor" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockNameEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockNameEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockTitleEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockTitleEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockImage" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageBackroundShape" ordered="false"
        unique="false" lowerBound="1" eType="#//ImageBackgroundShape"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasNextBlock" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageCursor" ordered="false"
        unique="false" eType="#//Cursor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageBackroundShapeColor"
        ordered="false" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="#FFFFFF"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasInfo" lowerBound="1"
        eType="#//Information" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Information">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="informationTextEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="informationTextEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cursor" ordered="false"
        unique="false" eType="#//Cursor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DecisionBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockImage" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfColumns" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockImageCursor" ordered="false"
        unique="false" eType="#//Cursor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSettingsPopover" eType="#//SettingsPopover"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasConfigurationPopover"
        eType="#//ConfigurationPopover" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionBlock" eSuperTypes="#//Block">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockTitleEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockTitleEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockImage" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasPopover" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="popoverIcon" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="popoverHelpTextEL" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="popoverHelpTextEN" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="titleBackroundColor" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="#975e11"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasInfo" lowerBound="1"
        eType="#//Information" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasInput" upperBound="-1"
        eType="#//InputBlock" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSettingsPopover" eType="#//SettingsPopover"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputBlock" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infoTextEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="infoTextEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iconCursor" ordered="false"
        unique="false" eType="#//Cursor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectInputBlock" eSuperTypes="#//InputBlock">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOptions" lowerBound="1"
        upperBound="-1" eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextInputBlock" eSuperTypes="#//InputBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueEL" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueEN" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerInputBlock" eSuperTypes="#//InputBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMinValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMaxValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noDefaultValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FloatInputBlock" eSuperTypes="#//InputBlock">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMaxValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMinValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noDefaultValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Popover" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="popoverTitleEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="popoverTitleEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationPopover" eSuperTypes="#//Popover">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasInput" lowerBound="1"
        upperBound="-1" eType="#//InputBlock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SettingsPopover" eSuperTypes="#//Popover">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasForm" lowerBound="1"
        eType="#//Form" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhrasesInputForm" eSuperTypes="#//Form">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholderEL" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="placeholderEN" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledInputForm" abstract="true" eSuperTypes="#//Form">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableNameEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableNameEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledTextInputForm" eSuperTypes="#//LabeledInputForm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueEN" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueEL" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledIntegerInputForm" eSuperTypes="#//LabeledInputForm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMaxValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMinValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noDefaultValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LabeledFloatInputForm" eSuperTypes="#//LabeledInputForm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMaxValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noMinValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="noDefaultValue" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterInputForm" eSuperTypes="#//Form">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueEL" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValueEN" ordered="false"
        unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOptions" lowerBound="1"
        upperBound="-1" eType="#//Option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionInputForm" eSuperTypes="#//Form">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOptions" lowerBound="1"
        upperBound="-1" eType="#//ConditionOption" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionTextEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionTextEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionOption">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionTextEL" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="optionTextEN" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparisonType" ordered="false"
        unique="false" lowerBound="1" eType="#//ComparisonType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparators" ordered="false"
        unique="false" upperBound="6" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasOptions" upperBound="-1"
        eType="#//Option" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
